name: 'Docker: Scan latest release image'

on:
  schedule:
    # Scan the image regularly (once a day).
    - cron: '44 4 * * *'

jobs:
  scan-debian:
    permissions:
      contents: read # For actions/checkout to fetch code.
      security-events: write # For github/codeql-action/upload-sarif to upload SARIF results.
    name: Debian - Scan current image & report results
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          vuln-type: "os"
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  scan-alpine:
    permissions:
      contents: read # For actions/checkout to fetch code.
      security-events: write # For github/codeql-action/upload-sarif to upload SARIF results.
    name: Alpine - Scan current image & report results
    runs-on: "ubuntu-latest"
    steps:
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:latest-alpine'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          vuln-type: "os"
      -
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'